version: '3.1'
services:
  frontend:
    restart: always
    build: ./my-frontend
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./my-frontend:/app
    environment:
      - WATCHPACK_POLLING=true

  api:
    restart: always
    build: ./api
    ports:
      - "5000:5000"
    volumes:
      - ./api:/app

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: very-strong-password
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: very-strong-password
    depends_on:
      - mongo

volumes:
  mongodb_data:
